/**
 * Writes prisma/seed-posts.sql: the "found and fixed" write-ups from
 * src/content/portfolio.ts as blog posts, so they show up in the admin panel (and can
 * be edited, unpublished or deleted there) instead of living only in the code.
 *
 *   npx tsx scripts/generate-posts-seed.ts
 *
 * Like the projects seed, it only INSERTS missing rows (ON CONFLICT DO NOTHING), so a
 * post you have since edited is never overwritten. A test fails if the file drifts.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { incidents, profile } from "../src/content/portfolio";

const slugify = (text: string) =>
  text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const html = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export const postSlug = (title: string) => slugify(title);

export function buildPostsSql(): string {
  const rows = incidents.items.map((it, i) => {
    const content = [
      "<h2>What happened</h2>",
      `<p>${html(it.happened)}</p>`,
      "<h2>What I changed</h2>",
      `<p>${html(it.changed)}</p>`,
      "<h2>The lesson</h2>",
      `<p>${html(it.lesson)}</p>`,
    ].join("");
    const values = [
      "gen_random_uuid()::text",
      q(it.title),
      q(postSlug(it.title)),
      q(content),
      q(it.lesson),
      "ARRAY['Lessons learnt']::TEXT[]",
      q(profile.name),
      "'published'",
      // Newest first on the blog: spread the dates so the order is stable.
      `now() - interval '${i} minutes'`,
    ];
    return `  (${values.join(", ")})`;
  });
  return [
    "-- Generated by scripts/generate-posts-seed.ts. Do not edit by hand.",
    "-- Inserts the lessons-learnt posts if they are not there yet; never overwrites.",
    'INSERT INTO "blog_posts"',
    '  ("id", "title", "slug", "content", "excerpt", "tags", "author", "status", "published_at")',
    "VALUES",
    rows.join(",\n"),
    'ON CONFLICT ("slug") DO NOTHING;',
    "",
  ].join("\n");
}

if (require.main === module) {
  const out = join(__dirname, "..", "prisma", "seed-posts.sql");
  writeFileSync(out, buildPostsSql());
  console.log(`wrote ${out}`);
}
