/**
 * Writes prisma/seed-projects.sql from the curated projects in
 * src/content/portfolio.ts, so the home page and /projects tell one story.
 *
 *   npx tsx scripts/generate-projects-seed.ts
 *
 * The SQL only INSERTS missing rows (ON CONFLICT DO NOTHING), so running it
 * again never overwrites a project you have since edited in the admin panel.
 * A test fails if the committed file drifts from the content file.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { profile, projects } from "../src/content/portfolio";

export const slugify = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const arr = (xs: string[]) =>
  xs.length ? `ARRAY[${xs.map(q).join(", ")}]::TEXT[]` : "ARRAY[]::TEXT[]";

/** First sentence, for the card summary. */
const excerptOf = (body: string) => {
  const first = body.split(/(?<=\.)\s/)[0] ?? body;
  return first.length > 220 ? `${first.slice(0, 217)}...` : first;
};

export function buildSeedSql(): string {
  const rows = projects.map((p) => {
    const github = p.links.find((l) =>
      l.href.startsWith("https://github.com/"),
    );
    const content = [p.body, p.note ? `\n\n${p.note}.` : ""].join("");
    const values = [
      "gen_random_uuid()::text",
      q(p.title),
      q(slugify(p.title)),
      q(content),
      q(excerptOf(p.body)),
      arr(p.stack),
      github ? q(github.href) : "NULL",
      q(profile.name),
      "'published'",
      "now()",
    ];
    return `  (${values.join(", ")})`;
  });
  return [
    "-- Generated by scripts/generate-projects-seed.ts. Do not edit by hand.",
    "-- Inserts the curated projects if they are not there yet; never overwrites.",
    'INSERT INTO "projects"',
    '  ("id", "title", "slug", "content", "excerpt", "technologies", "github_url", "author", "status", "published_at")',
    "VALUES",
    rows.join(",\n"),
    'ON CONFLICT ("slug") DO NOTHING;',
    "",
  ].join("\n");
}

if (require.main === module) {
  const out = join(__dirname, "..", "prisma", "seed-projects.sql");
  writeFileSync(out, buildSeedSql());
  console.log(`wrote ${out}`);
}
